#!/usr/bin/expect -f

set timeout -1
set password "bD?2\$2#TY-v*sx@9"

# Start the deployment script
spawn bash deploy_vultr.sh

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "Are you sure you want to continue connecting" {
        send "yes\r"
        exp_continue
    }
    "DELETED" {
        exp_continue
    }
    "sending incremental file list" {
        exp_continue
    }
    eof
}

catch wait result
exit [lindex $result 3]
